Algoritmo "contador 06"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 19/03/2024
Var
// Seção de Declarações das variáveis 
     numero: inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
     para numero de 500 ate 700 faca
        escreva(numero)
        fimpara




Fimalgoritmo